---
format: 
  html: 
    code-fold: true
    html-math-method: katex
pdf: 
    geometry: 
      - top=30mm
      - left=20mm
    template-partials: 
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
editor: source
bibliography: "C:/Users/LENOVO/Documents/GitHub/just-school/input/bib/just-school.bib"
link-citations: true
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: María Fernanda Núñez
    orcid: 0009-0004-7559-9959
    email: maria.nunez.2@ug.uchile.cl
    affiliations:
      - ref: 1
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 4
affiliations: 
  - id: 1
    name: Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: Pontificia Universidad Católica de Chile
lang: es
citeproc: true
---
[Propuesta corregida]

# Percepciones de Justicia en la Evaluación Escolar: Un Estudio Exploratorio en Estudiantes Chilenos

Este estudio investiga la percepción de justicia en las notas escolares desde la perspectiva de los estudiantes, un ámbito poco explorado en el contexto educativo chileno. La investigación se enmarca en la creciente preocupación por cómo se perciben las desigualdades en el sistema educativo, donde la justicia distributiva ha sido tradicionalmente analizada en el contexto de la población adulta y la distribución de salarios [@castillo_cual_2009]. Sin embargo, hasta ahora existe escasa evidencia sobre cómo los estudiantes perciben la equidad en la asignación de calificaciones.

En la escuela, los estudios sobre justicia han enfocado mayormente en el profesorado, considerando su preparación pedagógica y las tensiones dentro del sistema educativo chileno [@sleeterPreparingTeachersSocial2016; @barahonaChileanEFLStudent2024]. Asimismo, se ha explorado la relación entre justicia y movilidad social, destacando la influencia del principio meritocrático en la percepción de desigualdades [@mijs_unfulfillable_2016; @wiederkehr_belief_2015; @castillo_legitimacy_2011; @wilsonRoleMeritPrinciple2003]. Evidencia internacional sugiere que las percepciones de justicia en las calificaciones están estratificadas socioeconómicamente y varían según el género, con las estudiantes mujeres tendiendo a percibir sus notas como más justas en comparación con sus compañeros varones [@jassoExploringSenseJustice2002; @resh_sense_2010]. En Chile, estudios recientes muestran que las percepciones de desigualdad salarial entre estudiantes también median la relación entre su estatus social y las evaluaciones de justicia [@salgadoAdolescentsJusticeEvaluations2020].

Este estudio se propone explorar las sensaciones de (in)justicia de los estudiantes chilenos en sus notas, en un contexto educativo caracterizado por alta segregación y desigualdad. Para ello introduce un análisis de justicia en las notas escolares basado en el índice de evaluación de justicia [@jassoExploringSenseJustice2002; @resh_sense_2010], que mide la justicia (J) como el logaritmo del ratio entre la calificación obtenida por el estudiante y la que este considera justa. Este enfoque permite identificar tres posibles sensaciones: injusticia por sub-recompensa (J < 0), justicia perfecta (J = 0) e injusticia por sobre-recompensa (J > 0). Utilizando datos de la encuesta "Educación y Meritocracia - EDUMER" (N=902), se realizarán análisis descriptivos y bivariados para observar cómo las percepciones de justicia varían según género, curso, capital cultural, composición socioeconómica del hogar y creencias en la meritocracia. Finalmente, se presentarán modelos multivariados que exploren los efectos de estas variables en las evaluaciones de justicia escolar.




----
[Propuesta original]
### Aproximaciones a las sensación de justicia en las notas en estudiantes de enseñanza básica y media

¿En qué medida los/as estudiantes consideran que son justamente recompensados en sus notas? El ámbito de la justicia de recompensas ha sido ampliamente estudiado en Chile dentro de la agenda de investigación empíricia de la justicia distributiva, caracterizada por su visualización en la población adulta y remitida a la distribución de salarios [@castillo_cual_2009]. Contrariamente, esta ha sido una temática poco estudiada en población escolar. En la escuela, la justicia se ha trabajado primordialmente con población docente y remitiendo a temas asociados a su preparación pedagógica dentro del marco hostil que caracteriza el modelo educativo chileno [@sleeterPreparingTeachersSocial2016; @barahonaChileanEFLStudent2024]. Otro marco de investigación ha sido su vínculo con la estratificación y movilidad social [@castillo_cual_2009] y su relación con las percepciones de desigualdad a partir del principio distributivo meritocrático [@mijs_unfulfillable_2016; @wiederkehr_belief_2015; @castillo_legitimacy_2011; @wilsonRoleMeritPrinciple2003].

Para estudiar la justicia en el contexto escolar, se presenta el indicador de evaluación de justicia en las notas [@jassoExploringSenseJustice2002; @resh_sense_2010], donde la justicia (J) es entendida como la expresión logarítmica del ratio entre la nota que el estudiante obtuvo en razón con la nota que considera justa. Este índice nos permite observar la sensación de (in)justicia que tienen los estudiantes respecto a las notas que obtienen en su escuela, diferenciando tres sensaciones: injusticia por sub-recompensa (J \< 0), justicia perfecta (J = 0) e injusticia por sobre-recompensa (J \> 0).

La evidencia internacional sostiene que los logros académicos, las notas en la escuela y el sentimiento de (in)justicia de los/as estudiantes en estas se presentan de forma estratificada socioeconómicamente [@resh_sense_2010]. También, al diferenciar por el género de los/as estudiantes se observa que las mujeres tienden a considerar más justas las notas obtenidas, de modo que sus evaluaciones de justicia se inclinan hacia la sensación de justicia perfecta e injusticia por sobre-recompensa en comparación con sus pares hombres [@jassoExploringSenseJustice2002; @resh_sense_2010].

Dentro de los estudios que se han realizado a la población escolar en Chile, se presentan direcciones similares al observar las percepciones que tienen los/as estudiantes respecto a la desigualdad saliarial y su sensación de justicia, donde ambos funcionan como mediadores entre el estatus y el nivel de desigualdad que los/as estudiantes consideran justo, así se presentan implicancias en la legitimación de la desigualdad ancladas a su posición social [@salgadoAdolescentsJusticeEvaluations2020].

Bajo ese marco, este estudio se propone explorar las sensaciones de (in)justicia de los/as estudiantes en sus notas dentro de un contexto altamente segregador y desigual como lo es el caso chileno y, de ese modo, presentar un primer acercamiento a dichas percepciones considerando las particularidades sociodemográficas del estudiante. Para ello, se utilizarán los datos de la encuesta "Educación y Meritocracia - EDUMER" (N= 902), de la cual se observan variables referentes a percepciones de merecimiento y justicia. Se analizarán descriptvamente las variables de interés, para luego observar su comportamiento bivariado con atributos del estudiante referidos al género, curso, capital cultural, la composición socioeconómica de su hogar y sus creencias en la meritocracia escolar. Finalmente, se proponen modelos multivariados con el fin de observar los efectos de dichas características en sus evaluaciones de justicia en la escuela.
